### ISSUE TITLE
Panic when tailing old stream

### ISSUE THREAD

**Issue by raymondbutcher** [lucagrulla/cw#30]
Hi. Nice project, but I've hit a bug.

These streams exist:

```
$ cw ls streams /var/log/stuff/uat
access/instance1
access/instance2
catalina/instance1
catalina/instance2
localhost/instance1
localhost/instance2
```

But I can't tail some of them:

```
$ cw tail /var/log/stuff/uat localhost/instance2
No such log stream(s).
panic: send on closed channel

goroutine 42 [running]:
github.com/lucagrulla/cw/cloudwatch.(*CW).Tail.func4(0xc00001c780, 0xc00001c701, 0x412da2)
	/Users/lucagrulla/Projects/cw/cloudwatch/tail.go:149 +0x175
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).FilterLogEventsPagesWithContext(0xc00000c2a8, 0x7f6299adb130, 0xc000026120, 0xc00007d590, 0xc00001c6c0, 0x0, 0x0, 0x0, 0xc00016f101, 0xc00007d590)
	/Users/lucagrulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.14.17/service/cloudwatchlogs/api.go:2288 +0x116
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).FilterLogEventsPages(0xc00000c2a8, 0xc00007d590, 0xc00001c6c0, 0x0, 0x0)
	/Users/lucagrulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.14.17/service/cloudwatchlogs/api.go:2260 +0x90
github.com/lucagrulla/cw/cloudwatch.(*CW).Tail.func5(0xc00007e910, 0xc0000593c0, 0xc00016f1d0, 0xc000026ff8, 0x0, 0xc000059390, 0xc000026b47, 0xc00000c2b0, 0xc00001c6c0)
	/Users/lucagrulla/Projects/cw/cloudwatch/tail.go:174 +0x235
created by github.com/lucagrulla/cw/cloudwatch.(*CW).Tail
	/Users/lucagrulla/Projects/cw/cloudwatch/tail.go:170 +0x3b3
```

Unless I specify the date.

```
$ cw tail /var/log/stuff/uat localhost/instance2 2018-11-09T14:52
09-Nov-2018 14:52:17.320 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
09-Nov-2018 14:52:17.320 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
09-Nov-2018 14:52:17.321 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@62379589')
09-Nov-2018 14:52:20.921 INFO [main] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
09-Nov-2018 14:52:21.208 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
```

This stream hasn't had any activity for a few days, and that's the only difference I can think of between the broken streams and the working ones.

I'm using the latest release.
```
$ cw --version
2.1.1
```

**Comment by lucagrulla** [comment]
Hi,

Thanks for filing this.
I can see how it happens. I'm not sure about the fix though, I do need to check streams against timestamp for a limitation of the AWS API. I'll have a look.

**Comment by raymondbutcher** [comment]
Thanks!
